"use client";

import React from "react";
import Link from "next/link";

export default function PrivacyPolicy() {
  const blurUpClass = (delay: number) => 
    `transition-all duration-700 delay-${delay} opacity-0 animate-fade-in`;

  return (
    <div className="min-h-screen bg-black text-white font-body selection:bg-white/20">
      {/* Background Glows */}
      <div className="fixed top-[10%] left-[-10%] w-[50%] h-[50%] bg-white/5 rounded-full blur-[120px] pointer-events-none z-0"></div>
      <div className="fixed bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-white/5 rounded-full blur-[120px] pointer-events-none z-0"></div>

      <nav className="fixed top-4 left-0 right-0 z-50 px-8 lg:px-16 py-3 flex items-center justify-between">
        <Link href="/" className="h-12 w-12 flex-shrink-0 flex items-center justify-center transition-transform hover:scale-105 duration-300 liquid-glass rounded-full">
          <img src="/logo.svg" alt="Stokk Logo" className="h-full w-full object-contain" />
        </Link>
        
        <div className="hidden md:flex liquid-glass rounded-full px-1.5 py-1 items-center gap-1">
          <Link href="/" className="px-4 py-2 text-sm font-medium text-white/70 hover:text-white transition-colors">Home</Link>
          <a href="https://play.google.com/store/apps/details?id=com.virionplaysgg.stokk&hl=en" className="bg-white text-black rounded-full px-4 py-2 text-sm flex items-center gap-1 ml-2 font-bold hover:bg-gray-200 transition-colors">
            Download
          </a>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 pt-48 pb-32 relative z-10">
        <div className="mb-16">
          <div className={`liquid-glass rounded-full px-3.5 py-1 text-xs font-medium text-white/60 mb-6 inline-block ${blurUpClass(0)}`}>
            Legal Hub
          </div>
          <h1 className={`text-5xl md:text-7xl font-heading italic text-white leading-tight tracking-[-2px] mb-6 ${blurUpClass(200)}`}>
            Privacy Policy
          </h1>
          <p className={`text-white/50 font-light text-lg md:text-xl max-w-2xl ${blurUpClass(400)}`}>
            Effective immediately upon downloading Stokk. We take simulation seriously, and privacy even more seriously.
          </p>
        </div>

        <div className={`liquid-glass rounded-[2.5rem] p-8 md:p-12 space-y-12 ${blurUpClass(600)}`}>
          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">1. Introduction</h2>
            <p className="text-white/60 font-light leading-relaxed">
              Welcome to Stokk ("us", "we", or "our"), a premium simulated crypto trading terminal operating natively on Expo Go. This Privacy Policy outlines how we handle your data when you practice paper-trading across the market in our application. Because our assets and bankrolls are 100% simulated, our fundamental policy is data minimalization. 
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">2. Zero Real Financial Data</h2>
            <p className="text-white/60 font-light leading-relaxed">
              Because our application allows you to trade with fake money ("Stokk Tokens" or standard fiat simulations), we will <strong>never</strong> ask you to link a legitimate brokerage API, provide banking credentials, or expose credit card information. Your simulated portfolio balance is purely a mathematical state living in your localized app storage.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">3. What We Map and Store</h2>
            <p className="text-white/60 font-light leading-relaxed mb-4">
              In order to provide competitive leaderboards and progression tiers based on your tap count, we store:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-white/50 font-light">
              <li>An anonymous installation UUID generated by Expo upon initialization.</li>
              <li>Your current simulation milestones (e.g., tap count, acquired fake-crypto assets).</li>
              <li>Non-identifiable crash reports to stabilize the terminal environment.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">4. Third-Party Market Engines</h2>
            <p className="text-white/60 font-light leading-relaxed">
              While your money is completely simulated, to give you a hyper-authentic paper-trading environment, our application subscribes to real-time asset feeds. These feeds are strictly read-only incoming websocket packets providing global market variables. No personal data flows outward to these market engines.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">5. No Financial Advice</h2>
            <p className="text-white/60 font-light leading-relaxed">
              Stokk is strictly a simulation tool intended for entertainment and educational purposes only. Any interactions, simulated gains, simulated losses, or tiered progression within the application do not constitute financial, investment, or trading advice. Past performance within the simulator does not guarantee or indicate future performance in real-world markets. You agree that Stokk is not liable for any real-world financial decisions you make based on simulator activity.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">6. Disclaimer of Warranties and Liability</h2>
            <p className="text-white/60 font-light leading-relaxed">
              The application is provided "AS IS" and "AS AVAILABLE" without warranties of any kind. We explicitly disclaim any liability for potential data loss, service interruptions, or inaccuracies in the simulated pricing feed. You expressly agree that your use of the application is at your sole risk, and Stokk operators cannot be held liable for compensatory, direct, indirect, or consequential damages.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">7. Data Retention and Deletion</h2>
            <p className="text-white/60 font-light leading-relaxed">
              Your simulated progress consists of local device storage and/or anonymized database syncs attached entirely to randomly generated unique device identifiers. If you delete the Stokk application from your device, your local data is permanently eradicated. We reserve the right to prune or delete inactive UUIDs periodically without prior notice to maintain server stability.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">8. Age Restriction (COPPA Compliance)</h2>
            <p className="text-white/60 font-light leading-relaxed">
              Stokk is not intended for use by individuals under the age of 13, and we do not knowingly map or collect data from minors. Because the application involves simulated financial markets, we heavily restrict data mapping. If we become aware that an underage user's data has been logged, we will immediately execute protocols to delete said data.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">9. Changes and Severability</h2>
            <p className="text-white/60 font-light leading-relaxed">
              We reserve the unconditional right to modify this specific Privacy Policy and Terms of Use at any given time. If any provision within this document is found to be legally unenforceable by a competent jurisdiction, that specific provision shall be severed, and the remainder of the legal shields shall continue in full functional effect.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-heading italic text-white mb-4">10. Contacting Legal &amp; Support</h2>
            <p className="text-white/60 font-light leading-relaxed">
              By downloading, accessing, or interacting with the Stokk terminal, you fully acknowledge and accept the terms of this document. For inquiries regarding data minimalization protocols or legal correspondence, contact our administration directly at <a href="mailto:pigeon.software.2012@gmail.com" className="text-white underline underline-offset-4 decoration-white/20 hover:decoration-white transition-all">pigeon.software.2012@gmail.com</a>.
            </p>
          </section>
        </div>
      </main>

      <footer className="max-w-7xl mx-auto px-6 py-12 border-t border-white/10 flex flex-col md:flex-row items-center justify-between text-white/30 text-sm">
        <div className="mb-4 md:mb-0">&copy; 2026 Stokk App. All rights reserved.</div>
        <div className="flex gap-8">
          <Link href="/" className="hover:text-white transition-colors">Home</Link>
          <Link href="/auth" className="hover:text-white transition-colors">Auth</Link>
        </div>
      </footer>
    </div>
  );
}